/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estacionamento;

import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

public class estacionamentos extends javax.swing.JPanel {

        private final conectar bd;

        private final DefaultTableModel Estac;
    
    public estacionamentos(conectar BD) {
        bd = BD;
        initComponents();
        Estac = (DefaultTableModel) estacionamentoTab.getModel();
        idSelect = "";
        preencheTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nome = new javax.swing.JLabel();
        endereco = new javax.swing.JLabel();
        telefone = new javax.swing.JLabel();
        nomeTex = new javax.swing.JTextField();
        enderecoText = new javax.swing.JTextField();
        telefoneTex = new javax.swing.JTextField();
        guardarBt = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        estacionamentoTab = new javax.swing.JTable();
        referencia = new javax.swing.JLabel();
        referenciaTex = new javax.swing.JTextField();
        cidade = new javax.swing.JLabel();
        cidadeTex = new javax.swing.JTextField();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Estacionamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(51, 51, 51))); // NOI18N

        nome.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        nome.setText("Nome:");

        endereco.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        endereco.setText("Endereço:");

        telefone.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        telefone.setText("Telefone:");

        nomeTex.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        enderecoText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        telefoneTex.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        guardarBt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        guardarBt.setForeground(new java.awt.Color(51, 0, 51));
        guardarBt.setText("Guardar");
        guardarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtActionPerformed(evt);
            }
        });

        estacionamentoTab.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        estacionamentoTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Nome", "Endereço", "Telefone", "Referência", "Cidade", "Excluir", "Alterar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        estacionamentoTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estacionamentoTabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(estacionamentoTab);

        referencia.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        referencia.setText("Referência:");

        referenciaTex.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        cidade.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cidade.setText("Cidade:");

        cidadeTex.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nome, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(endereco, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(telefone, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nomeTex, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                .addComponent(enderecoText, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                .addComponent(telefoneTex, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(referencia)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(cidade)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cidadeTex, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(referenciaTex, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(guardarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome)
                    .addComponent(nomeTex, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecoText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endereco))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneTex, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(referenciaTex, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(referencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cidadeTex, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guardarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void guardarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtActionPerformed
        String nome, endereco, telefone, referencia, cidade;
        nome = nomeTex.getText();
        endereco = enderecoText.getText();
        telefone = telefoneTex.getText();
        referencia= referenciaTex.getText();
        cidade = cidadeTex.getText();
        
        System.out.println(nome);
        System.out.println(endereco);
        System.out.println(telefone);
        System.out.println(referencia);
        System.out.println(cidade);
        
        try {
            if(idSelect.equals("")){
                bd.persistir("INSERT INTO estacionamento(nome, endereco, telefone, referencia, cidade) "
                    + "VALUES('" + nome + "','" + endereco + "','" + telefone + "','" + referencia + "','" + cidade + "')");
            }else{
                bd.persistir("update estacionamento set "
                    + "nome = '" + nome + "'"
                    + ",endereco = '" + endereco + "'"
                    + ",telefone = '" + telefone + "' "
                    + ",referencia = '" + referencia + "' "
                    + ",cidade = '" + cidade + "' "
                    + "where id = '"+idSelect+"'");
            }
            idSelect = "";
            preencheTabel();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_guardarBtActionPerformed

    private void estacionamentoTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estacionamentoTabMouseClicked
        int li = estacionamentoTab.getSelectedRow();
        int col = estacionamentoTab.getSelectedColumn();
        String texto = (String) estacionamentoTab.getValueAt(li, col);
        String id = (String) estacionamentoTab.getValueAt(li, 0);
        idSelect = "";
        if(texto.equals("Exc")){
            excluir(id);
        }else if(texto.equals("Alt")){
            editar(id);
        }
        preencheTabel();
    }//GEN-LAST:event_estacionamentoTabMouseClicked

     public void excluir(String id){
        bd.persistir("DELETE FROM estacionamento where id = "+id);
    }
    public void editar(String id){
        ResultSet estacionamento;
        try{
        estacionamento =  bd.recupera("SELECT * FROM estacionamento where id = "+id);
        while(estacionamento.next()){
            this.idSelect = estacionamento.getString("id");
            this.nomeTex.setText(estacionamento.getString("nome"));
            this.enderecoText.setText(estacionamento.getString("endereco"));
            this.telefoneTex.setText(estacionamento.getString("telefone"));
            this.referenciaTex.setText(estacionamento.getString("referencia"));
            this.cidadeTex.setText(estacionamento.getString("cidade"));
        }
            
        }catch(Exception e){
            
        }
    }
    
    public void preencheTabel() {
        try {
            ResultSet todos = bd.recupera("select * from estacionamento");
            Estac.setNumRows(0);
            while (todos.next()) {
                String[] Nlinha = {
                    todos.getString("id"),
                    todos.getString("nome"),
                    todos.getString("endereco"),
                    todos.getString("telefone"),
                    todos.getString("referencia"),
                    todos.getString("cidade"),
                    "Exc", "Alt"
                };
                Estac.addRow(Nlinha);
            }
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }

    public ResultSet busca() {
        return bd.recupera("select * from estacionamento");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cidade;
    private javax.swing.JTextField cidadeTex;
    private javax.swing.JLabel endereco;
    private javax.swing.JTextField enderecoText;
    private javax.swing.JTable estacionamentoTab;
    private javax.swing.JToggleButton guardarBt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nome;
    private javax.swing.JTextField nomeTex;
    private javax.swing.JLabel referencia;
    private javax.swing.JTextField referenciaTex;
    private javax.swing.JLabel telefone;
    private javax.swing.JTextField telefoneTex;
    // End of variables declaration//GEN-END:variables
        
    private String idSelect;
}
