/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

/**
 *
 * @author dieisson
 */
public class questionario extends javax.swing.JPanel {

    /**
     * Creates new form questionario
     */
    public questionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cDQt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pergunta = new javax.swing.JTextArea();
        pg = new javax.swing.JLabel();
        alt1 = new javax.swing.JLabel();
        alt2 = new javax.swing.JLabel();
        alt3 = new javax.swing.JLabel();
        alt4 = new javax.swing.JLabel();
        alter4 = new javax.swing.JTextField();
        alter1 = new javax.swing.JTextField();
        alter2 = new javax.swing.JTextField();
        alter3 = new javax.swing.JTextField();
        botaoInserir = new javax.swing.JButton();

        cDQt.setText("Cadastro Questao ");

        pergunta.setColumns(20);
        pergunta.setRows(5);
        jScrollPane1.setViewportView(pergunta);

        pg.setText("Pergunta:");

        alt1.setText("Alternativa 1");

        alt2.setText("Alternativa 2");

        alt3.setText("Alternativa 3");

        alt4.setText("Alternativa 4");

        alter4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alter4ActionPerformed(evt);
            }
        });

        alter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alter1ActionPerformed(evt);
            }
        });

        alter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alter2ActionPerformed(evt);
            }
        });

        alter3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alter3ActionPerformed(evt);
            }
        });

        botaoInserir.setText("Inserir");
        botaoInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInserirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(alt1)
                                .addGap(18, 18, 18)
                                .addComponent(alter1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(pg)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(73, 73, 73))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(alt3)
                                .addGap(18, 18, 18)
                                .addComponent(alter3, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cDQt)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(alt2)
                                    .addGap(18, 18, 18)
                                    .addComponent(alter2, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(alt4)
                                    .addGap(18, 18, 18)
                                    .addComponent(alter4, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(247, 247, 247))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cDQt)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pg)
                        .addGap(64, 64, 64)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alter1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alt1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alter2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alt2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alter3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alt3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alter4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alt4))
                .addGap(18, 18, 18)
                .addComponent(botaoInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void alter4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alter4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alter4ActionPerformed

    private void alter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alter1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alter1ActionPerformed

    private void alter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alter2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alter2ActionPerformed

    private void alter3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alter3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alter3ActionPerformed

    private void botaoInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInserirActionPerformed
        String n, c, f, s, l;
        n = alter4.getText();
        c = campoCPF.getText();
        f = campoFiliacao.getText();
        s = radioFEM.isSelected() ? radioFEM.getText() : radioMASC.getText();
        l = (String) campoLazer.getSelectedItem();
        pTxAlvo.setText(pTxAlvo.getText() + "\nNome:" + n + "\nCPF:" + c + "\nFiliação:" + f + "\nLazer: " + l + "\nSexo:" + s);
        this.show("Nome:" + n + "\nCPF:" + c + "\nFiliação:" + f + "\nLazer: " + l + "\nSexo:" + s);
        this.limpa();
    }//GEN-LAST:event_botaoInserirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alt1;
    private javax.swing.JLabel alt2;
    private javax.swing.JLabel alt3;
    private javax.swing.JLabel alt4;
    private javax.swing.JTextField alter1;
    private javax.swing.JTextField alter2;
    private javax.swing.JTextField alter3;
    private javax.swing.JTextField alter4;
    private javax.swing.JButton botaoInserir;
    private javax.swing.JLabel cDQt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea pergunta;
    private javax.swing.JLabel pg;
    // End of variables declaration//GEN-END:variables
}
