/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

/**
 *
 * @author dieisson
 */
public class questao extends javax.swing.JPanel {

    /**
     * Creates new form questao
     */
    public questao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        letraA = new javax.swing.JRadioButton();
        letraC = new javax.swing.JRadioButton();
        letraB = new javax.swing.JRadioButton();
        letraD = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        letraA.setText("a)  alternativa1");
        letraA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraAActionPerformed(evt);
            }
        });

        letraC.setText("c)  alternativa3");
        letraC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraCActionPerformed(evt);
            }
        });

        letraB.setText("b)  alternativa2");
        letraB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraBActionPerformed(evt);
            }
        });

        letraD.setText("d)  alternativa4");
        letraD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraDActionPerformed(evt);
            }
        });

        jLabel1.setText("1 - texto da questao texto da questaotexto da questaotexto da questaotexto da questaotexto da questao ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(letraD)
                    .addComponent(letraB)
                    .addComponent(letraC)
                    .addComponent(letraA))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(letraA)
                .addGap(18, 18, 18)
                .addComponent(letraB)
                .addGap(18, 18, 18)
                .addComponent(letraC)
                .addGap(18, 18, 18)
                .addComponent(letraD)
                .addContainerGap(202, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void letraAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letraAActionPerformed

    private void letraCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letraCActionPerformed

    private void letraBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letraBActionPerformed

    private void letraDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letraDActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton letraA;
    private javax.swing.JRadioButton letraB;
    private javax.swing.JRadioButton letraC;
    private javax.swing.JRadioButton letraD;
    // End of variables declaration//GEN-END:variables
}
