Algoritmo "5 temratura"
// Disciplina  :  [Algoritmos] 
// Professor   : 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/05/2017
Var
// Seção de Declarações das variáveil
c,f:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite teperatura:")
leia(c)

f<-(9*C+160)/5

escreva("A temperatura",c,"C° covertida em Fahrenheit é igual á",f)

Fimalgoritmo