Algoritmo "semnome"
// Disciplina  :  [Algoritmos] 
// Professor   : 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/05/2017
Var
// Seção de Declarações das variáveis 
dolar,reeal,v:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("digite o valor desejado:")
leia(reeal)

escreva("digite valor de um dolar:")
leia(v)

Fimalgoritmo